--- #YAML:1.0
name:               ASP4
version:            1.081
abstract:           Fast, Simple, Scalable Web Development
author:
    - John Drago <jdrago_999@yahoo.com>
license:            artistic
distribution_type:  module
test_requires:
    Test::More:           0
    Test::Memory::Cycle:  0
    Time::HiRes:          0
    HTML::Form:           0
requires:
    common::sense:            0
    Data::Properties::YAML:   0
    Cwd:                      0
    Digest::MD5:              0
    DBI:                      0
    Ima::DBI::Contextual:     0
    Storable:                 0
    HTTP::Date:               0
    Time::HiRes               0
    Mail::Sendmail:           0
    CGI:                      3.43
    HTTP::Body:               0
    JSON::XS:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       Hand
resources:
  repository: git://github.com/jdrago999/ASP4.git
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
